package polygons

import "base:runtime"
import "core:fmt"
import "core:slice"

// The container storing all the pointers needed for the half-edge-DS
//
// TODO(jan): use statically sized array, since this is currently not optimal and uses way to many heap allocations
HeContainer :: struct {
	edges: [dynamic]^HeEdge,
	faces: [dynamic]^HeFace,
	nodes: [dynamic]^HeNode,
}

// A simple Edge in the HEDS
//
// `original_prev` is the previous edge in the original polygon loop where only one face existed. DO NOT OVERWRITE THIS
HeEdge :: struct {
	origin:        ^HeNode,
	face:          ^HeFace,
	next:          ^HeEdge,
	prev:          ^HeEdge,
	twin:          ^HeEdge,
	original_prev: ^HeEdge,
}

// A Node in the HEDS
HeNode :: struct {
	original_idx: int,
	edge:         ^HeEdge,
	position:     Vector2,
}

// A Face in the HEDS
HeFace :: struct {
	edge: ^HeEdge,
}


// NOTE(jan): this function was generated by claude code and was not checked thoroughly.
// It was only used for debugging memory issues in the half edge list
@(private)
he_validate :: proc(he: ^HeContainer) -> (ok: bool, errors: [dynamic]string) {
	errors = make([dynamic]string)
	ok = true

	// Helper to add error
	add_error :: proc(errors: ^[dynamic]string, ok: ^bool, msg: string) {
		append(errors, msg)
		ok^ = false
	}

	// 1. Validate all edges
	edges := he_get_edges(he)
	defer delete(edges)
	for &edge, i in edges {

		// Check origin exists
		if edge.origin == nil {
			add_error(&errors, &ok, fmt.aprintf("Edge %d has nil origin", i))
			continue
		}

		// Check face exists (can be nil for boundary edges)
		// if edge.face == nil {
		// 	add_error(&errors, &ok, fmt.aprintf("Edge %d has nil face", i))
		// }

		// Check twin exists and is mutual
		if edge.twin == nil {
			add_error(&errors, &ok, fmt.aprintf("Edge %d has nil twin", i))
		} else if edge.twin.twin != edge {
			add_error(
				&errors,
				&ok,
				fmt.aprintf(
					"Edge %d twin relationship broken (twin.twin != self), %p, %p",
					i,
					edge.twin.twin,
					edge.twin,
				),
			)
		}

		// Check next exists
		if edge.next == nil {
			add_error(&errors, &ok, fmt.aprintf("Edge %d has nil next", i))
		} else {
			// next.prev should point back to this edge
			if edge.next.prev != edge {
				add_error(&errors, &ok, fmt.aprintf("Edge %d next.prev chain broken", i))
			}

			// next.origin should be this edge's destination (twin.origin)
			if edge.twin != nil && edge.next.origin != edge.twin.origin {
				add_error(
					&errors,
					&ok,
					fmt.aprintf("Edge %d next.origin != twin.origin (connectivity broken)", i),
				)
			}
		}

		// Check prev exists
		if edge.prev == nil {
			add_error(&errors, &ok, fmt.aprintf("Edge %d has nil prev", i))
		} else {
			// prev.next should point to this edge
			if edge.prev.next != edge {
				add_error(&errors, &ok, fmt.aprintf("Edge %d prev.next chain broken", i))
			}
		}

		// If face exists, check all edges in cycle have same face
		if edge.face != nil {
			current := edge.next
			visited := make(map[^HeEdge]bool, context.temp_allocator)
			defer delete(visited)
			visited[edge] = true

			for current != nil && current != edge {
				if current in visited {
					add_error(
						&errors,
						&ok,
						fmt.aprintf("Edge %d face cycle has loop before returning to start", i),
					)
					break
				}
				visited[current] = true

				if current.face != edge.face {
					add_error(
						&errors,
						&ok,
						fmt.aprintf("Edge %d in face cycle has different face pointer", i),
					)
				}
				current = current.next
			}

			if current != edge {
				add_error(&errors, &ok, fmt.aprintf("Edge %d face cycle does not close", i))
			}
		}
	}

	// 2. Validate all nodes
	nodes := he_get_nodes(he)
	defer delete(nodes)
	for &node, i in nodes {

		// Check edge exists
		if node.edge == nil {
			add_error(&errors, &ok, fmt.aprintf("Node %d has nil edge", i))
			continue
		}

		// Check node.edge actually originates from this node
		if node.edge.origin != node {
			add_error(
				&errors,
				&ok,
				fmt.aprintf("Node %d edge.origin doesn't point back to node", i),
			)
		}

		// Check all outgoing edges from this node form a cycle via twin.next
		current := node.edge
		visited := make(map[^HeEdge]bool, context.temp_allocator)
		defer delete(visited)
		visited[current] = true

		for {
			if current.origin != node {
				add_error(
					&errors,
					&ok,
					fmt.aprintf(
						"Node %d outgoing edge cycle contains edge with different origin",
						i,
					),
				)
				break
			}

			if current.twin == nil {
				add_error(&errors, &ok, fmt.aprintf("Node %d outgoing edge has nil twin", i))
				break
			}

			current = current.twin.next
			if current == node.edge {
				break
			}

			if current in visited {
				add_error(
					&errors,
					&ok,
					fmt.aprintf("Node %d outgoing edges have cycle before returning to start", i),
				)
				break
			}
			visited[current] = true
		}
	}

	// 3. Validate all faces
	faces := he_get_faces(he)
	defer delete(faces)
	for &face, i in faces {

		// Check inner edge exists
		if face.edge == nil {
			add_error(&errors, &ok, fmt.aprintf("Face %d has nil inner edge", i))
			continue
		}

		// Check face.inner.face points back to this face
		if face.edge.face != face {
			add_error(
				&errors,
				&ok,
				fmt.aprintf("Face %d inner edge doesn't point back to face", i),
			)
		}

		// Traverse face cycle and ensure it's closed and all edges point to this face
		current := face.edge
		visited := make(map[^HeEdge]bool, context.temp_allocator)
		defer delete(visited)
		visited[current] = true
		edge_count := 1

		for {
			if current.face != face {
				add_error(
					&errors,
					&ok,
					fmt.aprintf("Face %d contains edge with different face pointer", i),
				)
			}

			current = current.next
			if current == face.edge {
				break
			}

			if current in visited {
				add_error(
					&errors,
					&ok,
					fmt.aprintf("Face %d edge cycle has loop before returning to start", i),
				)
				break
			}
			visited[current] = true
			edge_count += 1

			if edge_count > len(he.edges) {
				add_error(
					&errors,
					&ok,
					fmt.aprintf("Face %d edge cycle too long (infinite loop?)", i),
				)
				break
			}
		}

		// A valid face should have at least 3 edges
		if edge_count < 3 {
			add_error(
				&errors,
				&ok,
				fmt.aprintf("Face %d has only %d edges (need at least 3)", i, edge_count),
			)
		}
	}

	return ok, errors
}

// push a new node into the HEDS by allocating a new Node on the heap
he_empty_push_node :: proc(
	he: ^HeContainer,
	allocator: runtime.Allocator = context.allocator,
) -> (
	^HeNode,
	int,
) {
	node := new(HeNode)
	_ = append(&he.nodes, node)
	idx := len(he.nodes) - 1
	return node, idx
}

// push a new face into the HEDS by allocating a new Face on the heap
he_empty_push_face :: proc(he: ^HeContainer) -> (^HeFace, int) {
	face := new(HeFace)
	_ = append(&he.faces, face)
	idx := len(he.faces) - 1
	return face, idx
}

// push a new edge into the HEDS by allocating a new Edge on the heap
he_empty_push_edge :: proc(he: ^HeContainer) -> (^HeEdge, int) {
	edge := new(HeEdge)
	_ = append(&he.edges, edge)
	idx := len(he.edges) - 1
	return edge, idx
}


he_init_empty :: proc(he: ^HeContainer, allocator: runtime.Allocator = context.allocator) {
	he.nodes = make([dynamic]^HeNode, allocator)
	he.edges = make([dynamic]^HeEdge, allocator)
	he.faces = make([dynamic]^HeFace, allocator)
}

// Initialze a half edge datastructure for a polygon
// If `cw` == false, reverse the direction of edges to make sure that the HEDS is always stored in CCW
he_init_from_polygon :: proc(
	he: ^HeContainer,
	outline: Polygon,
	cw: bool = true,
	temp_allocator: runtime.Allocator = context.temp_allocator,
) -> bool {
	// in order to create a face, you need at least 3 verticies
	if len(outline) <= 2 {
		return false
	}

	face, face_idx := he_empty_push_face(he)
	first_node, first_node_idx := he_empty_push_node(he)
	first_node.position = outline[0]
	first_node.original_idx = 0

	created_edges := make([dynamic]^HeEdge, 0, len(outline), temp_allocator)
	defer delete(created_edges)

	last_node := first_node
	start := 1
	step := 1
	cond := proc(i: int, l: int) -> bool {return i < l}
	if !cw {
		start = len(outline) - 1
		step = -1
		cond = proc(i: int, l: int) -> bool {return i >= 1}
	}
	for i := start; cond(i, len(outline)); i += step {
		current_node, _ := he_empty_push_node(he)
		current_node.position = outline[i]
		current_node.original_idx = i

		edge, _ := he_empty_push_edge(he)
		edge.origin = last_node
		edge.face = face
		last_node.edge = edge
		// Fill twin, next and prev finally
		append(&created_edges, edge)

		last_node = current_node
	}
	// Push edge between first and last
	edge, _ := he_empty_push_edge(he)
	edge.origin = last_node
	edge.face = face
	last_node.edge = edge
	// Fill twin, next and prev finally
	append(&created_edges, edge)

	created_twin_edges := make([dynamic]^HeEdge, 0, len(created_edges), temp_allocator)
	defer delete(created_twin_edges)

	// connect next and previous of inner circle and create outer twin edges
	for i in 0 ..< len(created_edges) {
		a := created_edges[i]
		b := created_edges[(i + 1) % len(created_edges)]
		face.edge = a

		a.next = b
		b.prev = a
		b.original_prev = a

		twin_edge, _ := he_empty_push_edge(he)
		twin_edge.origin = b.origin
		twin_edge.twin = a
		twin_edge.face = nil
		append(&created_twin_edges, twin_edge)

		a.twin = twin_edge
	}

	// Reverse twin edges, because they are directed the opposite way that the normal edges are directed
	slice.reverse(created_twin_edges[:])
	// connect twin edges
	for i in 0 ..< len(created_twin_edges) {
		a := created_twin_edges[i]
		b := created_twin_edges[(i + 1) % len(created_twin_edges)]

		a.next = b
		b.prev = a
		b.original_prev = a
	}

	return true
}

// Query all edges that are outgoing from node. Use simple twin.next iteration until node.edge is reached again
he_query_all_outgoing_edges :: proc(node: ^HeNode, debug: bool = false) -> []^HeEdge {
	nodes := make([dynamic]^HeEdge, context.temp_allocator)
	defer delete(nodes)

	start_edge := node.edge
	append(&nodes, start_edge)

	current_edge := start_edge
	for {
		if current_edge == nil {
			break
		}

		if debug {
			fmt.println("Current Edge: ", current_edge)
			fmt.println("Current Edge.twin: ", current_edge.twin)
		}

		current_edge = current_edge.twin.next
		if current_edge == start_edge {
			break
		}
		append(&nodes, current_edge)
	}

	return slice.clone(nodes[:])
}

// Query the outgoing edge of node for a given face, or nil, false if there is no outgoing edge of node for the face
he_query_outgoing_edge_for_face :: proc(
	node: ^HeNode,
	face: ^HeFace,
	debug: bool = false,
) -> (
	^HeEdge,
	bool,
) {
	outgoing_edges := he_query_all_outgoing_edges(node, debug)
	defer delete(outgoing_edges)

	for edge in outgoing_edges {
		if edge.face == face {
			return edge, true
		}
	}

	return nil, false
}

// Get all faces that a node can reach using outgoing edges out of node without hops
he_query_all_faces_for_node :: proc(node: ^HeNode) -> map[^HeFace]bool {
	outgoing_edges := he_query_all_outgoing_edges(node)
	defer delete(outgoing_edges)

	set := make(map[^HeFace]bool)

	for edge in outgoing_edges {
		if edge.face != nil {
			set[edge.face] = true
		}
	}

	return set
}

// Find a face, that both a and b can reach without hops
he_match_face_for_node :: proc(a, b: ^HeNode) -> (^HeFace, bool) {
	a_faces := he_query_all_faces_for_node(a)
	b_faces := he_query_all_faces_for_node(b)
	defer delete(a_faces)
	defer delete(b_faces)


	for k, v in a_faces {
		if k in b_faces {
			// return face that matches both
			return k, true
		}
	}

	return nil, false
}

// Split a single face, that is determined to be a shared face of start end end.
// A new edge is created between start->end. and its twin is routed from end->start.
// The Edgeloop starting from start is assigned to the new face
he_split_face_by_nodes :: proc(
	he: ^HeContainer,
	start: ^HeNode,
	end: ^HeNode,
	debug: bool = false,
) {
	common_face, ok := he_match_face_for_node(start, end)
	if !ok {
		return
	}
	if debug {
		fmt.println("Common Face:", common_face)
	}


	// Get previous edges
	end_edge, end_found := he_query_outgoing_edge_for_face(end, common_face, debug)
	if !end_found {return}
	end_prev := end_edge.prev
	if debug {
		fmt.println("End Edge:", end_edge)
		fmt.println("End.prev Edge:", end_prev)
	}

	start_edge, start_found := he_query_outgoing_edge_for_face(start, common_face, debug)
	if !start_found {return}
	start_prev := start_edge.prev
	if debug {
		fmt.println("Start Edge:", start_edge)
		fmt.println("Start.prev Edge:", start_prev)
	}

	if start_edge.next == end_edge ||
	   start_edge.prev == end_edge ||
	   end_edge.next == start_edge ||
	   end_edge.prev == start_edge {
		return
	}

	new_edge, _ := he_empty_push_edge(he)
	new_twin, _ := he_empty_push_edge(he)
	if debug {
		fmt.println("new_edge:", new_edge)
		fmt.println("new_twin:", new_twin)
	}

	new_edge.twin = new_twin
	new_twin.twin = new_edge
	new_edge.origin = start
	new_twin.origin = end

	start.edge = new_edge
	end.edge = new_twin

	// Reconnect edges
	start_prev.next = new_edge
	new_edge.prev = start_prev
	new_edge.next = end_edge
	end_edge.prev = new_edge

	end_prev.next = new_twin
	new_twin.prev = end_prev
	new_twin.next = start_edge
	start_edge.prev = new_twin

	new_face, _ := he_empty_push_face(he)
	old_face := common_face

	current_edge := end_prev
	old_face.edge = end_prev
	for {
		current_edge.face = old_face

		current_edge = current_edge.next
		if current_edge == end_prev {
			break
		}
	}

	current_edge = start_prev
	new_face.edge = start_prev
	for {
		current_edge.face = new_face

		current_edge = current_edge.next
		if current_edge == start_prev {
			break
		}
	}
}

he_get_nodes :: proc(he: ^HeContainer) -> []^HeNode {
	return slice.clone(he.nodes[:])
}

he_get_faces :: proc(he: ^HeContainer) -> []^HeFace {
	return slice.clone(he.faces[:])
}

he_get_edges :: proc(he: ^HeContainer) -> []^HeEdge {
	return slice.clone(he.edges[:])
}

// Ger all edges for a single face
he_collect_edges_for_face :: proc(face: ^HeFace) -> []^HeEdge {
	edges := make([dynamic]^HeEdge, context.temp_allocator)
	defer delete(edges)

	start := face.edge
	append(&edges, start)

	// loop in a circle
	current := start
	for {
		current = current.next
		if current == start {
			break
		}

		append(&edges, current)
	}


	return slice.clone(edges[:])
}

he_print_face :: proc(face: ^HeFace, idx: int = 0) {
	edges := he_collect_edges_for_face(face)
	defer delete(edges)

	fmt.printf("Face %d: ", idx)
	for edge in edges {
		fmt.printf("%d->", edge.origin.original_idx)
	}
	fmt.printf("\n")
}

he_print :: proc(he: ^HeContainer) {
	faces := he_get_faces(he)
	defer delete(faces)

	for face, i in faces {
		he_print_face(face, i)
	}
}

// Destroy the container and all heap allocated data
he_destroy :: proc(he: ^HeContainer) {
	for e in he.edges {
		free(e)
	}
	for f in he.faces {
		free(f)
	}
	for n in he.nodes {
		free(n)
	}
	delete(he.edges)
	delete(he.faces)
	delete(he.nodes)
}
